# Generated by Django 5.0.6 on 2024-05-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='roles',
            new_name='role',
        ),
    ]
